export type CourseKind = 'grow' | 'earn';
export type Language = 'es' | 'en';

export const courseContent = {
  es: {
    home: 'Inicio',
    courses: 'Formación',
    program: 'El programa',
    materials: 'Qué incluye',
    questions: 'Preguntas',
    skip: 'Saltar al contenido',
    theme: 'Cambiar tema',
    menu: 'Abrir menú',
    close: 'Cerrar menú',
    back: 'Volver al inicio',
    by: 'UNA FORMACIÓN DE MARÍA BEGUÉ',
    browse: 'Explorar el programa',
    enroll: 'Ver oferta oficial',
    priceNote: 'Precio publicado en la web oficial. Confirma las condiciones antes de comprar.',
    language: 'Formación en español',
    pace: 'A tu ritmo',
    video: 'de vídeo',
    programEyebrow: '01 / DE LA IDEA A LA ACCIÓN',
    programTitle: 'Menos improvisación.',
    programAccent: 'Más intención.',
    programIntro: 'Explora los temas de la formación y encuentra dónde quieres poner el foco.',
    themeLabel: 'Explorar un tema',
    topic: 'TEMA',
    materialsEyebrow: '02 / LO QUE TE LLEVAS',
    materialsTitle: 'Aprende. Aplica.',
    materialsAccent: 'Vuelve cuando lo necesites.',
    materialsIntro: 'Contenido y recursos para acompañar la práctica.',
    audienceEyebrow: 'TU PUNTO DE PARTIDA',
    audienceTitle: '¿Es para ti?',
    instructorEyebrow: '03 / APRENDE CON MARÍA',
    instructorTitle: 'Al otro lado también',
    instructorAccent: 'hay una persona.',
    instructorText:
      'María comparte su experiencia como consultora de marca personal y creadora de contenido. Su propuesta conecta el desarrollo profesional con una pregunta personal: ¿qué quieres construir?',
    instructorLink: 'Conoce a María',
    instructorAlt: 'María Begué sonriendo con un libro',
    faqTitle: 'Antes de empezar.',
    faqEyebrow: 'LAS COSAS CLARAS',
    faqs: [
      {
        q: '¿Cómo compro y accedo al curso?',
        a: 'El botón de oferta te lleva a la web oficial de María. Allí puedes confirmar el precio, las condiciones y el proceso de acceso. Esta propuesta no procesa pagos.',
      },
      {
        q: '¿En qué idioma está la formación?',
        a: 'La formación se presenta en español. El selector ES / EN traduce esta página informativa; no traduce el contenido del curso.',
      },
      {
        q: '¿Qué resultados puedo esperar?',
        a: 'La formación no garantiza resultados. Aplicar lo aprendido, tu experiencia y tu constancia influyen en lo que puedas conseguir.',
      },
      {
        q: '¿Dónde consulto las condiciones y devoluciones?',
        a: 'Revisa las condiciones vigentes en la página oficial antes de comprar. Si necesitas aclaraciones, utiliza los canales de contacto de María.',
      },
    ],
    finalEyebrow: 'TU SIGUIENTE CAPÍTULO',
    finalTitle: 'Haz espacio para',
    finalAccent: 'lo que viene.',
    other: 'También puedes explorar',
    disclaimer:
      'Concepto independiente de rediseño por Cristian Torres. Compras y acceso en la web oficial de María Begué.',
    reference: 'Consultar fuente oficial',
    snapshot: 'Información revisada el 16 de septiembre de 2026.',
    grow: {
      title: 'Crece tu LinkedIn',
      word: 'Crece.',
      deck: 'TU VOZ. MÁS LEJOS.',
      hero: 'No publiques',
      accent: 'para el vacío.',
      intro:
        'Dale a tus ideas una forma que invite a quedarse. Empieza a construir una presencia que se recuerde.',
      price: 97,
      minutes: '80 min',
      number: '01',
      path: 'crece-tu-linkedin',
      otherPath: 'monetiza-tu-linkedin',
      otherTitle: 'Monetiza tu LinkedIn',
      ribbon: ['CONTENIDO', 'CONVERSACIÓN', 'COMUNIDAD'],
      audience: [
        'Ya publicas y quieres afinar tu contenido.',
        'Quieres desarrollar una audiencia en LinkedIn.',
        'Buscas ideas para salir del estancamiento.',
      ],
      topics: [
        {
          title: 'Abrir conversaciones',
          short: 'Conecta',
          intro: 'Contenido que invita a participar.',
          points: [
            'Interacciones y comentarios.',
            'Publicaciones que se comparten.',
            'Engagement con intención.',
          ],
        },
        {
          title: 'Escribir para que te lean',
          short: 'Crea',
          intro: 'Haz que sea más fácil seguir tu idea.',
          points: ['Escritura online.', 'Contenido fácil de consumir.', 'Atención y claridad.'],
        },
        {
          title: 'Desarrollar tu audiencia',
          short: 'Crece',
          intro: 'Dale dirección a tu visibilidad.',
          points: [
            'Expresar tus opiniones.',
            'Difusión del contenido.',
            'Visibilidad para tu negocio.',
          ],
        },
      ],
      resources: [
        {
          number: '80',
          unit: 'MINUTOS',
          title: 'Contenido en vídeo',
          text: 'Formación online sobre contenido y audiencia.',
        },
        {
          number: '2',
          unit: 'PLANTILLAS',
          title: 'Más de 50 infografías',
          text: 'Recursos visuales para acompañar tus ideas.',
        },
        {
          number: '20',
          unit: 'PÁGINAS',
          title: 'Guía de escritura',
          text: 'Un recurso para escribir online.',
        },
        {
          number: '+',
          unit: 'RECURSOS',
          title: 'Ideas para poner en práctica',
          text: 'Guía de viralización y diez mantras sobre audiencia.',
        },
      ],
    },
    earn: {
      title: 'Monetiza tu LinkedIn',
      word: 'Monetiza.',
      deck: 'LO QUE SABES. LO QUE PUEDES.',
      hero: 'Lo que sabes',
      accent: 'puede ser tu comienzo.',
      intro:
        'Ponle dirección a tu experiencia. Explora una forma de construir algo propio alrededor de lo que puedes aportar.',
      price: 67,
      minutes: '90 min',
      number: '02',
      path: 'monetiza-tu-linkedin',
      otherPath: 'crece-tu-linkedin',
      otherTitle: 'Crece tu LinkedIn',
      ribbon: ['EXPERIENCIA', 'PROPUESTA', 'OPORTUNIDAD'],
      audience: [
        'Quieres dar forma a una oferta propia.',
        'Te interesa un negocio alrededor de tu experiencia.',
        'Buscas los fundamentos de una marca personal.',
      ],
      topics: [
        {
          title: 'Un perfil con intención',
          short: 'Posiciona',
          intro: 'Un lugar claro para presentar tu trabajo.',
          points: [
            'Optimizar los elementos del perfil.',
            'Comunicar tu propuesta.',
            'Preparar tu presencia profesional.',
          ],
        },
        {
          title: 'Una estrategia de contenido',
          short: 'Comunica',
          intro: 'Decide qué decir y cómo compartirlo.',
          points: ['Escritura online.', 'Generación de ideas.', 'Interacciones estratégicas.'],
        },
        {
          title: 'Tu temática y tu oferta',
          short: 'Construye',
          intro: 'Conecta tu experiencia con una propuesta.',
          points: [
            'Elegir tu temática.',
            'Definir y validar una oferta.',
            'Marca personal y ventas.',
          ],
        },
      ],
      resources: [
        {
          number: '90',
          unit: 'MINUTOS',
          title: 'Contenido en vídeo',
          text: 'Formación online sobre perfil, contenido y oferta.',
        },
        {
          number: '3',
          unit: 'GUÍAS',
          title: 'Más de 20 páginas',
          text: 'Recursos escritos para profundizar.',
        },
        {
          number: '9',
          unit: 'TIPOS',
          title: 'Plantilla de contenido',
          text: 'Diferentes enfoques para tus publicaciones.',
        },
        {
          number: '+',
          unit: 'RECURSOS',
          title: 'De la idea a la práctica',
          text: 'Una checklist y diez mantras de marca personal.',
        },
      ],
    },
  },
  en: {
    home: 'Home',
    courses: 'Learning',
    program: 'The program',
    materials: 'What’s included',
    questions: 'Questions',
    skip: 'Skip to content',
    theme: 'Switch theme',
    menu: 'Open menu',
    close: 'Close menu',
    back: 'Back to home',
    by: 'A COURSE BY MARÍA BEGUÉ',
    browse: 'Explore the program',
    enroll: 'View official offer',
    priceNote: 'Price listed on the official website. Confirm the terms before purchasing.',
    language: 'Taught in Spanish',
    pace: 'At your own pace',
    video: 'of video',
    programEyebrow: '01 / FROM IDEA TO ACTION',
    programTitle: 'Less guesswork.',
    programAccent: 'More intention.',
    programIntro: 'Explore the course topics and find where you want to focus.',
    themeLabel: 'Explore a topic',
    topic: 'TOPIC',
    materialsEyebrow: '02 / YOUR TOOLKIT',
    materialsTitle: 'Learn. Apply.',
    materialsAccent: 'Come back when you need to.',
    materialsIntro: 'Content and resources to support your practice.',
    audienceEyebrow: 'YOUR STARTING POINT',
    audienceTitle: 'Is it for you?',
    instructorEyebrow: '03 / LEARN WITH MARÍA',
    instructorTitle: 'There’s a person',
    instructorAccent: 'on the other side.',
    instructorText:
      'María shares her experience as a personal brand consultant and content creator. Her approach connects professional development with a personal question: what do you want to build?',
    instructorLink: 'Get to know María',
    instructorAlt: 'María Begué smiling with a book',
    faqTitle: 'Before you begin.',
    faqEyebrow: 'LET’S MAKE IT CLEAR',
    faqs: [
      {
        q: 'How do I buy and access the course?',
        a: 'The offer button takes you to María’s official website to confirm pricing, terms and access. This concept does not process payments.',
      },
      {
        q: 'What language is the course in?',
        a: 'The course is presented in Spanish. The ES / EN selector translates this information page, not the course materials.',
      },
      {
        q: 'What results can I expect?',
        a: 'The course does not guarantee results. How you apply the material, your experience and your consistency influence what you can achieve.',
      },
      {
        q: 'Where can I check the terms and refunds?',
        a: 'Review the current conditions on the official page before purchasing. For clarification, use María’s contact channels.',
      },
    ],
    finalEyebrow: 'YOUR NEXT CHAPTER',
    finalTitle: 'Make room for',
    finalAccent: 'what comes next.',
    other: 'You can also explore',
    disclaimer:
      'Independent redesign concept by Cristian Torres. Purchases and access on María Begué’s official website.',
    reference: 'View official source',
    snapshot: 'Information reviewed on September 16, 2026.',
    grow: {
      title: 'Grow your LinkedIn',
      word: 'Grow.',
      deck: 'YOUR VOICE. FURTHER.',
      hero: 'Don’t publish',
      accent: 'into the void.',
      intro:
        'Give your ideas a form that makes people want to stay. Start building a presence worth remembering.',
      price: 97,
      minutes: '80 min',
      number: '01',
      path: 'crece-tu-linkedin',
      otherPath: 'monetiza-tu-linkedin',
      otherTitle: 'Monetize your LinkedIn',
      ribbon: ['CONTENT', 'CONVERSATION', 'COMMUNITY'],
      audience: [
        'You already post and want to refine your content.',
        'You want to develop a LinkedIn audience.',
        'You’re looking for a way out of a creative rut.',
      ],
      topics: [
        {
          title: 'Start conversations',
          short: 'Connect',
          intro: 'Content that invites participation.',
          points: ['Interactions and comments.', 'Shareable posts.', 'Intentional engagement.'],
        },
        {
          title: 'Write to be read',
          short: 'Create',
          intro: 'Make your ideas easier to follow.',
          points: ['Online writing.', 'Readable content.', 'Attention and clarity.'],
        },
        {
          title: 'Develop your audience',
          short: 'Grow',
          intro: 'Give your visibility direction.',
          points: [
            'Expressing your opinions.',
            'Content distribution.',
            'Visibility for your business.',
          ],
        },
      ],
      resources: [
        {
          number: '80',
          unit: 'MINUTES',
          title: 'Video content',
          text: 'Online training on content and audiences.',
        },
        {
          number: '2',
          unit: 'TEMPLATES',
          title: 'Over 50 infographics',
          text: 'Visual resources to support your ideas.',
        },
        {
          number: '20',
          unit: 'PAGES',
          title: 'Writing guide',
          text: 'A resource for writing online.',
        },
        {
          number: '+',
          unit: 'RESOURCES',
          title: 'Ideas to put into practice',
          text: 'A virality guide and ten audience-building mantras.',
        },
      ],
    },
    earn: {
      title: 'Monetize your LinkedIn',
      word: 'Monetize.',
      deck: 'WHAT YOU KNOW. WHAT YOU CAN DO.',
      hero: 'What you know',
      accent: 'could be your beginning.',
      intro:
        'Give your experience a direction. Explore a way to build something of your own around what you can offer.',
      price: 67,
      minutes: '90 min',
      number: '02',
      path: 'monetiza-tu-linkedin',
      otherPath: 'crece-tu-linkedin',
      otherTitle: 'Grow your LinkedIn',
      ribbon: ['EXPERIENCE', 'PROPOSITION', 'OPPORTUNITY'],
      audience: [
        'You want to shape an offer of your own.',
        'You’re interested in a business around your experience.',
        'You want personal branding fundamentals.',
      ],
      topics: [
        {
          title: 'A profile with purpose',
          short: 'Position',
          intro: 'A clear place to present your work.',
          points: [
            'Optimizing profile elements.',
            'Communicating your proposition.',
            'Preparing your professional presence.',
          ],
        },
        {
          title: 'A content strategy',
          short: 'Communicate',
          intro: 'Decide what to say and how to share it.',
          points: ['Online writing.', 'Generating ideas.', 'Strategic interactions.'],
        },
        {
          title: 'Your niche and your offer',
          short: 'Build',
          intro: 'Connect your experience to a proposition.',
          points: [
            'Choosing your niche.',
            'Defining and validating an offer.',
            'Personal branding and sales.',
          ],
        },
      ],
      resources: [
        {
          number: '90',
          unit: 'MINUTES',
          title: 'Video content',
          text: 'Online training on profiles, content and offers.',
        },
        {
          number: '3',
          unit: 'GUIDES',
          title: 'Over 20 pages',
          text: 'Written resources to explore further.',
        },
        {
          number: '9',
          unit: 'TYPES',
          title: 'Content template',
          text: 'Different approaches to your posts.',
        },
        {
          number: '+',
          unit: 'RESOURCES',
          title: 'From idea to practice',
          text: 'A checklist and ten personal branding mantras.',
        },
      ],
    },
  },
};
