export const content = {
  es: {
    proofLine: 'Marca personal.',
    proofAccent: 'Personas primero.',
    skip: 'Saltar al contenido',
    about: 'Sobre mí',
    work: 'Trabajemos juntos',
    courses: 'Cursos',
    newsletter: 'Newsletter',
    start: 'Empecemos',
    menu: 'Abrir menú',
    close: 'Cerrar menú',
    theme: 'Cambiar a tema',
    dark: 'oscuro',
    light: 'claro',
    eyebrow: 'MARCA PERSONAL · LINKEDIN · PROPÓSITO',
    hero1: 'Tu próxima',
    hero2: 'oportunidad',
    hero3: 'empieza en ti.',
    intro:
      'Convierte lo que sabes en una marca que conecta. Y tu marca, en una vida con más posibilidades.',
    primary: 'Potencia tu marca',
    secondary: 'Hola, soy María',
    portrait: 'María Begué con un libro, sonriendo',
    role: 'Consultora de marca personal',
    note: 'Menos ruido. Más tú.',
    scroll: 'DESCUBRE TU SIGUIENTE PASO',
    followers: 'personas en LinkedIn',
    readers: 'lectores de la newsletter',
    session: 'minutos para enfocarte',
    pathLabel: '01 / TU SIGUIENTE CAPÍTULO',
    pathTitle: 'Tienes algo que aportar.',
    pathAccent: 'Hagamos que se vea.',
    pathIntro:
      'Estés empezando o quieras dar un salto, encuentra una forma de avanzar que encaje contigo.',
    callTag: 'ESTRATEGIA CONTIGO',
    callTitle: 'Una hora.\nUn nuevo enfoque.',
    callText:
      'Una Power Call de 60 minutos para trabajar en tu perfil, tu contenido o tu posicionamiento en LinkedIn.',
    callLink: 'Descubre la consultoría',
    growTag: 'CONSTRUYE TU AUDIENCIA',
    growTitle: 'Crece tu\nLinkedIn.',
    growText:
      'Aprende a transformar tus ideas en contenido que invite a leer, conversar y compartir.',
    growLink: 'Explora el curso',
    earnTag: 'ABRE NUEVAS POSIBILIDADES',
    earnTitle: 'Monetiza tu\nLinkedIn.',
    earnText:
      'Explora cómo convertir tu conocimiento en una oferta y desarrollar un negocio alrededor de tu marca.',
    earnLink: 'Explora el curso',
    official: 'Información y disponibilidad en la web oficial.',
    aboutLabel: '02 / LA PERSONA DETRÁS',
    aboutTitle: 'Hola, soy María.',
    aboutAccent: 'Y creo en tu potencial.',
    aboutText:
      'Soy consultora de marca personal en LinkedIn y creadora de contenido sobre desarrollo personal y negocios online.',
    aboutText2:
      'Mi trabajo une dos cosas que me importan: compartir lo que aprendo y ayudar a otras personas a encontrar nuevas oportunidades. Porque crecer profesionalmente también puede acercarte a la vida que quieres.',
    aboutLink: 'Conoce mi trabajo',
    aboutImage: 'María Begué con una taza de café',
    aboutCaption: 'Marca personal. Con mucho de personal.',
    newsletterLabel: '03 / UNA PAUSA PARA CRECER',
    newsletterTitle: 'Buenas ideas.',
    newsletterAccent: 'Mejores comienzos.',
    newsletterText:
      'Ideas sobre marca personal y mentalidad, para leer con tu café y poner en práctica a tu ritmo.',
    newsletterButton: 'Quiero recibir la newsletter',
    newsletterNote: 'Gratis · Lectura de 5 minutos · Suscripción en la web oficial',
    edition: 'UNA CARTA PARA TI',
    letterTitle: 'Construye lo que quieres.',
    letterText:
      'Una idea puede cambiar cómo ves las cosas. Lo que haces con ella puede cambiar lo que viene después.',
    letterFooter: 'Nos leemos,',
    faqLabel: 'ANTES DE DAR EL PASO',
    faqTitle: 'Quizá te lo estás preguntando.',
    faqs: [
      {
        q: '¿Por dónde empiezo?',
        a: 'Si buscas orientación para tu situación concreta, explora la consultoría. Si prefieres aprender a tu ritmo, descubre los cursos. La newsletter es una forma gratuita de empezar a conocer el contenido de María.',
      },
      {
        q: '¿Qué puedo trabajar en una Power Call?',
        a: 'La sesión de 60 minutos está orientada a estrategia de contenido, optimización del perfil, posicionamiento y crecimiento de audiencia en LinkedIn. Consulta los detalles y la disponibilidad en la página oficial de consultorías.',
      },
      {
        q: '¿Dónde me inscribo en los cursos?',
        a: 'Los botones de cada curso te llevan a la web oficial de María. Allí encontrarás el programa, el precio actualizado, las condiciones y el acceso a la formación.',
      },
      {
        q: '¿Esta es la web oficial de María?',
        a: 'Esta es una propuesta independiente de rediseño creada por Cristian Torres. No está afiliada ni avalada por María Begué. Las reservas, las compras y las suscripciones se realizan en su web oficial.',
      },
    ],
    footerTitle: 'Tu voz merece',
    footerAccent: 'su espacio.',
    footerLink: 'Da el primer paso',
    footerSub: 'Marca personal con intención.',
    back: 'Volver arriba',
    credit:
      'Concepto de rediseño por Cristian Torres. Proyecto independiente, no afiliado a María Begué.',
    source: 'Visitar web oficial',
    statsNote: 'Cifras publicadas en la web original.',
  },
  en: {
    proofLine: 'Personal branding.',
    proofAccent: 'Human first.',
    skip: 'Skip to content',
    about: 'About me',
    work: 'Work with me',
    courses: 'Courses',
    newsletter: 'Newsletter',
    start: 'Let’s begin',
    menu: 'Open menu',
    close: 'Close menu',
    theme: 'Switch to',
    dark: 'dark theme',
    light: 'light theme',
    eyebrow: 'PERSONAL BRAND · LINKEDIN · PURPOSE',
    hero1: 'Your next',
    hero2: 'opportunity',
    hero3: 'starts with you.',
    intro:
      'Turn what you know into a brand that connects. And your brand into a life with more possibilities.',
    primary: 'Build your personal brand',
    secondary: 'Hi, I’m María',
    portrait: 'María Begué smiling while holding a book',
    role: 'Personal brand consultant',
    note: 'Less noise. More you.',
    scroll: 'DISCOVER YOUR NEXT STEP',
    followers: 'people on LinkedIn',
    readers: 'newsletter readers',
    session: 'minutes to find focus',
    pathLabel: '01 / YOUR NEXT CHAPTER',
    pathTitle: 'You have something to offer.',
    pathAccent: 'Let’s make it visible.',
    pathIntro:
      'Whether you’re getting started or ready for your next chapter, find a way forward that feels right for you.',
    callTag: 'STRATEGY, TOGETHER',
    callTitle: 'One hour.\nA fresh perspective.',
    callText: 'A 60-minute Power Call to work on your profile, content or positioning on LinkedIn.',
    callLink: 'Explore consulting',
    growTag: 'BUILD YOUR AUDIENCE',
    growTitle: 'Grow your\nLinkedIn.',
    growText: 'Learn to turn your ideas into content that people want to read, discuss and share.',
    growLink: 'Explore the course',
    earnTag: 'CREATE NEW POSSIBILITIES',
    earnTitle: 'Monetize your\nLinkedIn.',
    earnText:
      'Explore how to turn your knowledge into an offer and build a business around your personal brand.',
    earnLink: 'Explore the course',
    official: 'Details and availability on the official website (Spanish).',
    aboutLabel: '02 / THE PERSON BEHIND THE BRAND',
    aboutTitle: 'Hi, I’m María.',
    aboutAccent: 'And I believe in your potential.',
    aboutText:
      'I’m a LinkedIn personal brand consultant and a content creator focused on personal development and online business.',
    aboutText2:
      'My work brings together two things I care about: sharing what I learn and helping others discover new opportunities. Because professional growth can also bring you closer to the life you want.',
    aboutLink: 'Get to know my work',
    aboutImage: 'María Begué holding a cup of coffee',
    aboutCaption: 'Personal branding. Emphasis on personal.',
    newsletterLabel: '03 / A MOMENT TO GROW',
    newsletterTitle: 'Good ideas.',
    newsletterAccent: 'Better beginnings.',
    newsletterText:
      'Thoughts on personal branding and mindset to enjoy with your coffee and put into practice at your own pace.',
    newsletterButton: 'Sign up for the newsletter',
    newsletterNote: 'Free · A 5-minute read · Official signup · Written in Spanish',
    edition: 'A LETTER FOR YOU',
    letterTitle: 'Build what you want.',
    letterText:
      'One idea can change how you see things. What you do with it can change what comes next.',
    letterFooter: 'Until next time,',
    faqLabel: 'BEFORE YOUR NEXT STEP',
    faqTitle: 'You might be wondering.',
    faqs: [
      {
        q: 'Where should I start?',
        a: 'For guidance on your own situation, explore consulting. If you prefer self-paced learning, discover the courses. The free newsletter is a simple way to get to know María’s content.',
      },
      {
        q: 'What can I work on in a Power Call?',
        a: 'The 60-minute session focuses on content strategy, profile optimization, positioning and audience growth on LinkedIn. See the official consulting page for details and availability.',
      },
      {
        q: 'Where do I enroll in a course?',
        a: 'Each course button takes you to María’s official website in Spanish, where you can review the curriculum, current pricing, terms and course access.',
      },
      {
        q: 'Is this María’s official website?',
        a: 'This is an independent redesign concept created by Cristian Torres. It is not affiliated with or endorsed by María Begué. Bookings, purchases and subscriptions take place on her official website.',
      },
    ],
    footerTitle: 'Your voice deserves',
    footerAccent: 'to be heard.',
    footerLink: 'Take the first step',
    footerSub: 'Personal branding with purpose.',
    back: 'Back to top',
    credit:
      'Redesign concept by Cristian Torres. Independent project, not affiliated with María Begué.',
    source: 'Visit official website',
    statsNote: 'Figures published on the original website.',
  },
};
